######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 15 03:57:16 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += AlphaNumEncoder.h \
           APLT.h \
           CC_Table.h \
           ECC_Table.h \
           ECCgenerator.h \
           Encoder.h \
           Interleaver.h \
           ModuleMatrix.h \
           NumEncoder.h \
           Parser.h \
           QRCode.h \
           QRCodeGenerator.h \
           Rem_Table.h \
           Viewer.h
SOURCES += AlphaNumEncoder.cpp \
           APLT.cpp \
           CC_Table.cpp \
           ECC_Table.cpp \
           ECCgenerator.cpp \
           Encoder.cpp \
           Interleaver.cpp \
           ModuleMatrix.cpp \
           NumEncoder.cpp \
           Parser.cpp \
           QRCodeGenerator.cpp \
           qrgen.cpp \
           Rem_Table.cpp \
           Viewer.cpp
